server.port : 8888
spring.datasource.url : jdbc:mysql://localhost:3306/db_exam
spring:  datasource:    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:    database: MYSQL
    show-sql: true
  
  data:    rest:      base-path: /api
